"""11c Phase 0: reproduce 11a Phase 4's trade log and attach entry-time-only
features (NEXT_PROMPT.md sec 6, their v4 sec 14.3's proposal).

Reruns the exact same pre-declared trading rule, on the same five live
spreads and the same dev window, as `run_phase_4_11a_control_book.py` --
11a's own trade log is not persisted to a committed file (it is a >$1M-book,
57-trade in-memory object regenerated by that script and by 11a's own Phase 5
trade-atlas script), so this notebook regenerates it identically rather than
inventing a new one. Label: did the trade exit via stop (the -6.94 ATR
population in the external atlas, `exit_reason == "stop"`) or via z-score
normalization (`exit_reason == "zscore"`).

Every feature is computed from data strictly available before the trade's
own entry bar (the same `.shift(1)` / trailing-window discipline
`compute_zscore`/`compute_atr_series` already use), so none of them could
leak the trade's own outcome.

Writes phase_0_11c_results.json (57 trades x ~13 features -- small enough to
commit in full, unlike a raw parquet/price series).
"""

import json
import sys

sys.path.insert(0, "src/research/tmp")
sys.path.insert(0, "src")

import commod_lib8 as C8
import numpy as np
import polars as pl
import research_lib9 as R9
import spread_lib10 as S10
import spread_lib11 as S11

SPREAD_DIR = "src/research/data/market/spreads"
FRED_DFF_PATH = "src/research/data/market/fred/DFF.parquet"
OUT_PATH = "src/research/tmp/phase_0_11c_results.json"
DEV_END = "2024-12-31"

LIVE_SPREADS = [
    "brent_wti",
    "brent_calendar",
    "corn_wheat",
    "bean_corn",
    "kc_chicago_wheat",
]
STOP_ATR_OVERRIDES = {"brent_calendar": 4.0, "kc_chicago_wheat": 12.0}
REGIME_REQUIREMENTS = {"brent_calendar": "backwardation"}

# Same MID storage constant 11b used as its headline BF bucket boundary --
# not swept here either (sec 4.1's "priors, not swept" discipline extends to
# every parameter this notebook borrows from the pre-declared rule).
STORAGE_MID = S11.STORAGE_MID
FEATURE_WINDOW = 252


def load_frames() -> dict[str, pl.DataFrame]:
    frames = {}
    for name in LIVE_SPREADS:
        df = pl.read_parquet(f"{SPREAD_DIR}/{name}.parquet")
        df = df.filter(pl.col("date") <= pl.lit(DEV_END).str.to_date()).sort("date")
        frames[name] = df
    return frames


def dff_financing_rate(dates: np.ndarray) -> np.ndarray:
    """Cached FRED DFF, shifted 1 day, /100, forward-filled and reindexed
    onto `dates` -- same construction as 11b's Gate BF (sec 3 Phase 1's own
    instruction to prefer real DFF over the 0.05 constant)."""
    dff = (
        pl.read_parquet(FRED_DFF_PATH)
        .with_columns(pl.col("date").cast(pl.Date))
        .sort("date")
    )
    dff = dff.with_columns((pl.col("DFF").shift(1) / 100.0).alias("financing_rate"))
    joined = pl.DataFrame({"date": dates}).join(
        dff.select(["date", "financing_rate"]), on="date", how="left"
    )
    joined = joined.with_columns(pl.col("financing_rate").fill_null(strategy="forward"))
    return joined["financing_rate"].to_numpy().astype(float)


def build_trade_features(name: str, df: pl.DataFrame, trades: list[dict]) -> list[dict]:
    dates = df["date"].to_numpy()
    value = df["value"].to_numpy().astype(float)
    leg1 = df["leg1_price"].to_numpy().astype(float)
    leg2 = df["leg2_price"].to_numpy().astype(float)
    roll_flag = df["roll_window_flag"].to_numpy().astype(bool)
    p = S11.TradingRuleParams()

    vol_pct = S11._suppression_masks(value, roll_flag, p)["vol_pct"]
    financing = dff_financing_rate(dates)
    full_carry = S11.compute_carry_fv(leg2, STORAGE_MID, financing)
    # Sign convention resolved in 11b: their "+1 at contango ceiling"
    # requires negating this repo's literal carry_ratio.
    carry_corrected = -S11.carry_ratio(value, full_carry)

    log_leg1 = np.concatenate([[np.nan], np.diff(np.log(leg1))])
    log_leg2 = np.concatenate([[np.nan], np.diff(np.log(leg2))])
    leg_corr = S10.rolling_leg_correlation(log_leg1, log_leg2, window=60)

    date_index = {d: i for i, d in enumerate(dates)}
    out = []
    for t in trades:
        i = date_index[t["entry_date"]]
        hist_start = max(0, i - FEATURE_WINDOW)
        hist = value[hist_start:i]
        hist = hist[np.isfinite(hist)]

        adf_stat = float("nan")
        half_life = None
        stability = {
            "n_subperiods_in_band": 0,
            "n_subperiods": 0,
            "full_sample_in_band": False,
        }
        vr5 = float("nan")
        vr20 = float("nan")
        hurst = float("nan")
        if len(hist) >= 60:
            adf_stat = float(S10.adf_test(hist)["t_stat"])
            fit = R9.ols_ar1_diff(hist)
            half_life = fit.get("half_life_days")
            stability = S11.rolling_stability(hist)
            vr5 = S11.variance_ratio(hist, q=5)["z_stat"]
            vr20 = S11.variance_ratio(hist, q=20)["z_stat"]
            hurst = S11.hurst_exponent(hist)

        level_pctile = float("nan")
        if len(hist) >= 2:
            level_pctile = float((hist < value[i - 1]).mean())

        atr_i = t["entry_atr"]
        pre_move_5 = float("nan")
        pre_move_20 = float("nan")
        if i - 6 >= 0 and atr_i:
            pre_move_5 = float((value[i - 1] - value[i - 6]) / atr_i)
        if i - 21 >= 0 and atr_i:
            pre_move_20 = float((value[i - 1] - value[i - 21]) / atr_i)

        out.append(
            {
                "spread": name,
                "entry_date": str(t["entry_date"]),
                "exit_reason": t["exit_reason"],
                "label_stop": int(t["exit_reason"] == "stop"),
                "entry_abs_z": abs(float(t["entry_z"])),
                "carry_ratio_corrected": float(carry_corrected[i])
                if np.isfinite(carry_corrected[i])
                else None,
                "vol_pctile": float(vol_pct[i]) if np.isfinite(vol_pct[i]) else None,
                "adf_stat": adf_stat if np.isfinite(adf_stat) else None,
                "rolling_half_life": half_life,
                "half_life_stability_frac": (
                    stability["n_subperiods_in_band"] / stability["n_subperiods"]
                    if stability["n_subperiods"] > 0
                    else None
                ),
                "full_sample_in_band": int(stability["full_sample_in_band"]),
                "roll_proximity": int(roll_flag[i]),
                "leg_correlation": float(leg_corr[i - 1])
                if i - 1 >= 0 and np.isfinite(leg_corr[i - 1])
                else None,
                "variance_ratio_z_q5": float(vr5) if np.isfinite(vr5) else None,
                "variance_ratio_z_q20": float(vr20) if np.isfinite(vr20) else None,
                "hurst": float(hurst) if np.isfinite(hurst) else None,
                "spread_level_pctile": level_pctile
                if np.isfinite(level_pctile)
                else None,
                "pre_move_5_atr": pre_move_5 if np.isfinite(pre_move_5) else None,
                "pre_move_20_atr": pre_move_20 if np.isfinite(pre_move_20) else None,
            }
        )
    return out


def main() -> None:
    frames = load_frames()
    p = S11.TradingRuleParams()
    params = {n: p for n in LIVE_SPREADS}
    book = S11.simulate_book(
        frames,
        params,
        STOP_ATR_OVERRIDES,
        REGIME_REQUIREMENTS,
        C8.round_turn_cost_per_contract,
    )

    records = []
    for name, df in frames.items():
        spread_trades = book["per_spread"][name]["trades"]
        records.extend(build_trade_features(name, df, spread_trades))
    records.sort(key=lambda r: r["entry_date"])

    feature_names = [
        "entry_abs_z",
        "carry_ratio_corrected",
        "vol_pctile",
        "adf_stat",
        "rolling_half_life",
        "half_life_stability_frac",
        "full_sample_in_band",
        "roll_proximity",
        "leg_correlation",
        "variance_ratio_z_q5",
        "variance_ratio_z_q20",
        "hurst",
        "spread_level_pctile",
        "pre_move_5_atr",
        "pre_move_20_atr",
    ]
    n_complete = sum(1 for r in records if all(r[f] is not None for f in feature_names))

    out = {
        "n_trades": len(records),
        "n_stop": sum(r["label_stop"] for r in records),
        "n_zscore": len(records) - sum(r["label_stop"] for r in records),
        "n_trades_all_features_finite": n_complete,
        "feature_names": feature_names,
        "storage_constant": "MID",
        "feature_window": FEATURE_WINDOW,
        "trades": records,
        "_note": (
            "Reproduces 11a Phase 4's control book exactly (same params, "
            "spreads, dev window, cost model); every feature uses only data "
            "at or before the trade's own entry bar."
        ),
    }
    with open(OUT_PATH, "w") as f:
        json.dump(out, f, indent=2, default=str)

    print(
        f"Phase 0 (11c): n_trades={out['n_trades']} n_stop={out['n_stop']} "
        f"n_zscore={out['n_zscore']} n_complete_feature_rows={n_complete}"
    )


if __name__ == "__main__":
    main()
